name: app_lifecycle_observer
description: Flutter lifecycle observer independent of context.
version: 0.0.2
repository: https://github.com/aakira/app_lifecycle_observer
issue_tracker: https://github.com/aakira/app_lifecycle_observer/issues
homepage: https://github.com/aakira/app_lifecycle_observer

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
